### ISSUE TITLE
More colors in UI

### ISSUE THREAD

**Issue by Ilithy** [kaajjo/Libre-Sudoku#20]
Hi;

Your application is excellent but, _(in my opinion)_ sorely lacking in colors that would make the game board "less cold" and much more pleasant.
Would it be possible to add options for coloring the game board, the background, the numbers, position lines etc? With an accentuation of the chosen color _(with the theme already present in the app, and the dynamic model)_

_To give an example of what this "could" look like:_

![IMG_20230123_092510](https://user-images.githubusercontent.com/36798218/213994715-473a77f2-4b51-4a33-ad13-5bba96977554.jpg)
##### Capture shamefully recovered from [Sudoku](https://github.com/Lemkinator/Sudoku) ^^

What do you think about this?
Thanks ❤️

**Comment by yaomtc** [comment]
I'd like for my inputs to be different in color from the given numbers. Difficult to see my progress currently

**Comment by kaajjo** [comment]
Completed in afbf997 and 656603a

**Comment by yaomtc** [comment]
Still can't tell them apart very well in the dynamic theme.
![Screenshot_20230223-194052](https://user-images.githubusercontent.com/5534045/221084637-1f69cfe6-ee88-41cf-878e-befe6e64d7d9.png)

**Comment by kaajjo** [comment]
@yaomtc,
Yeah, I see. It doesn't look good with bluish accent colors, my bad. It's hard to find a balance to make it look good with very different accent colors, I will change it, stay tuned
