### ISSUE TITLE
Weblate?

### ISSUE THREAD

**Issue by d4f5409d** [kaajjo/Libre-Sudoku#3]

**Comment by kaajjo** [comment]
Done, It is now available for translation at https://hosted.weblate.org/projects/libresudoku/

**Comment by shuvashish76** [comment]
`This project is in a trial period, be cautious while contributing. Setup can still change before being approved as a libre project.`

Please keep this issue open till they approve as a libre project.

**Comment by kaajjo** [comment]
The project has been approved as a libre project. The link is still the same https://hosted.weblate.org/projects/libresudoku/
