### ISSUE TITLE
Layout rebuild

### ISSUE THREAD

**Issue by nvllz** [kaajjo/Libre-Sudoku#5]
Hi, it's my first issue here! I really like your app. I'll definitely spend some time on it. But while it's cool in terms of gameplay, there are many flaws in the layout. The biggest problem is a grid that is too bold and bright compared to the numbers in dark mode. This makes the view too vague at first glance. You need to concentrate on the numbers, not the bold, bright lines. Another thing I see is a problem with alignment. Some of the cell contents seem to be misaligned, which looks a bit bad. The buttons for each number below the grid are also unevenly aligned and too small. These are my suggestions:

### [THE MAIN MENU]
- [ ] the main menu is completely inconsistent right now.. it would be better to present all the options on the screen in the form of small buttons in two rows
- [x] place the 'Continue' button above the 'Play'
- [x] if it's possible to resume an existing game, make the background color of the "Play" button less accentuated (like the background color of the "Home" button at the bottom)
- [x] show details of the game that can be continued (grid size, difficulty, elapsed time)
- [x] remember last game's level and mode (now it is always easy/9x9 by default)

### [SUDOKU BOARD]
- [x] make the main grid thinner, with a low opacity for black/dark modes
- [x] add a possiblity to place the function buttons directly below the grid, over number buttons
- [ ] fix note alignment within each cell
- [x] enlarge the number buttons below the grid and align them correctly - move the grid and difficulty/time labels bit higher if needed
- [x] balance the hue of all numbers - make notes a bit grayer than regular numbers, make the hue of entered numbers a bit different from the original ones

### [GAME COMPLETION SCREEN]
- [x] I think it is a little too static right now. Just a message to return to the main menu or stay on the grid. It would be cool to see some details like the game timer, the number of errors (x/3 if enabled), a prompt for a new time record, etc. It definitely needs a redesign. I would see it as a dialog that says the game is over with buttons to either 'show details' or 'return to menu'. It would be cool to have a smooth transition here, which would really fit in with all the other smooth aspects of the app. If we choose to stay on the grid, we will see the same finished grid screen as before, but with the toolbar hidden, as the numbers are now hidden. In their place, the game can display statistics, the best time for the current mode, etc. Now staying on the grid gives you almost nothing, because you can see more game details in the history tab. Such a thing could make the aftergame screen more interesting

### [HISTORY]
- [x] fix the sort dialog being covered by the navigation bar at the bottom of the screen
- [x] I think it would look better if the 'Current' and 'Initial' tabs were merged, or the initial numbers were shaded slightly differently to those added by the player
- [x] make the 'Progress' label show progress as a percentage
- [x] change the title bar text of the game entry view from 'Saved game' to 'Game #id'
- [x] remove a trailing space in the time label (now it's "Time:  20:30" with two spaces after the colon)
- [x] display the time in the format "HH:MM:SS" if the elapsed time exceeds one hour (01:20:30 instead of 80:30), and apply the same to the 'Statistics' entries
- [x] remove the check mark in the sort dialog for items that act as radio buttons (Either "ID" or "Timer" sorting must be selected, so the check mark is misleading because you can't uncheck them. Leave these marks for actual checkboxes only, as it is clearly visible which option is selected for radio-like buttons)

### [SETTINGS]
- [ ] short 'Dark Theme' option label text to just 'Theme', rename the options: 'Off' to 'Light' and 'On' to 'Dark'

The app is almost perfect. I hope you understand what I'm trying to say and that these things will one day make it into the app. Thanks for your efforts ;)

**Comment by kaajjo** [comment]
Thanks for such a big feedback ❤️
What about notes. First I checked calculations, they seem to be right. Then I went to photoshop and measured the pixels and alignments. For me, all notes aligned properly vertically/horizontally and have the same height/weight. Maybe I'm just misunderstanding what you mean

**Comment by kaajjo** [comment]
Fixed sort dialog being covered by navbar in [5f4c490](https://github.com/kaajjo/Libre-Sudoku/commit/5f4c4903b8b1bab2bc45e1b1283b07e28bb7ffd0)

**Comment by kaajjo** [comment]
> make the 'Progress' label show progress as a percentage
> change the title bar text of the game entry view from 'Saved game' to 'Game #id'

Done in [0c3fa39](https://github.com/kaajjo/Libre-Sudoku/commit/0c3fa3970a62fe9f268fd88efdcc446e1d5a191a)

**Comment by Ilithy** [comment]
> I think it would look better if the 'Current' and 'Initial' tabs were merged, and the initial numbers were shaded slightly differently to those added by the player

I don't agree with this at all, personally I find it very useful to have these two separate screens, however it would be great to have an option to switch the display the way you describe it, if it's possible.

Thanks
