### ISSUE TITLE
Sorting dialog placement in history tab

### ISSUE THREAD

**Issue by nvllz** [kaajjo/Libre-Sudoku#57]
Here you can see a little bug with the dialog, as it's placed slightly above the status bar, while it was sticked to it before: 

![](https://user-images.githubusercontent.com/110673332/235427154-ae0ab64c-33fc-4df4-a23d-c55cc70a085c.jpg)

Also I think it'd be better to have a tickmark inside "Ascending/Descending" button when checked.

**Comment by kaajjo** [comment]
Strange, does not happen to me
![Screenshot_20230503-220944](https://user-images.githubusercontent.com/87094439/236020200-3409b498-48c4-424c-a635-014d9b08cff2.png)
What's your android and oneui (I think it's oneui?) version? How does it look with the gesture navigation?
