### ISSUE TITLE
Add Killer Sudoku mode

### ISSUE THREAD

**Issue by PlexSheep** [kaajjo/Libre-Sudoku#63]
Would it be possible to add a mode for killer sudoku? (Basically add boxes which display the sums of their elements.)

I might take up on this and fork if I can make some time.

**Comment by PlexSheep** [comment]
Started a fork over at [my profile](https://github.com/PlexSheep/Libre-Sudoku/).

I have no experience with android developement yet, but I've gotten the app to run on my system and want this to happen :)

**Comment by kaajjo** [comment]
I tried a long time ago to make an algorithm that will generate these boxes in real time for given boards, but after several tries I gave up.
But that's very interesting

**Comment by PlexSheep** [comment]
I thought a bit about it, and did some research on how to generate a killer sudoku:

1. Basically, we cheat a bit. Fill a Grid with a valid combination first. This get's stored as the solution, so we don't have to calculate it manually.
2. "Invent" the cages for killer sudoku
3. Depending on the selected difficulty, throw all of, or only a part of the generated grid away.

That way we have both a solution and a valid killer sudoku. Sadly, this is not perfect, as killer sudokus can have multiple solutions. Impementing this would also not fit in perfectly, as I saw you store the sudoku grid with an int array. I think this would not work for a killer sudoku, as we have to store both the numbers that are in our killer sudoku, which cage each tile belongs to, and the sum of the cage.

Sadly, I'm not exactly proficient with developing of android apps, that does not help too.
